---

certbot_certs:

  - cert_name: monki.biz
    email: andrius.cepaitis@gmail.com
    webroot_path: /var/www/certbot
    domains:
      - monki.biz
      - www.monki.biz

  - cert_name: zulu.cepaitis.eu
    email: andrius.cepaitis@gmail.com
    webroot_path: /var/www/certbot
    domains:
      - zulu.cepaitis.eu
      - jenkins.cepaitis.eu
      - monit.cepaitis.eu
      - munin.cepaitis.eu
      - portainer.cepaitis.eu
      - prometheus.cepaitis.eu
      - registry.cepaitis.eu
      - aha.cepaitis.eu
      - t1.cepaitis.eu
      - t2.cepaitis.eu
      - t3.cepaitis.eu

proxy_sites:
- default
- jenkins
- monki.biz
- portainer
- aha
- t1

...


# smm.cepaitis.eu
# smm-dev.cepaitis.eu
# smm-test.cepaitis.eu
